# Generated by Django 5.0.3 on 2024-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationnews',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
