# Generated by Django 5.0.3 on 2024-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_corporationnews_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationnews',
            name='text',
            field=models.TextField(default='Text News'),
        ),
    ]
