# Generated by Django 5.0.3 on 2024-06-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_writer_newscomments_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomments',
            old_name='author',
            new_name='writer',
        ),
    ]
